<?php
const NFL_TEAM_COLORS = [
    "49ers" => "#aa0000",
    "Bears" => "#c73701",
    "Bengals" => "#fb4f14",
    "Bills" => "#00348d",
    "Broncos" => "#fb4f13",
    "Browns" => "#ff3c00",
    "Buccaneers" => "#a71930",
    "Cardinals" => "#97233f",
    "Chargers" => "#0080c6",
    "Chiefs" => "#e31837",
    "Colts" => "#002c5f",
    "Commanders" => "#5a1214",
    "Cowboys" => "#012244",
    "Dolphins" => "#008e97",
    "Eagles" => "#004c54",
    "Falcons" => "#a71930",
    "Giants" => "#0b2265",
    "Jaguars" => "#006375",
    "Jets" => "#003f2d",
    "Lions" => "#0076b6",
    "Packers" => "#203732",
    "Panthers" => "#0085ca",
    "Patriots" => "#003366",
    "Raiders" => "#090909",
    "Rams" => "#003594",
    "Ravens" => "#2b1c8c",
    "Saints" => "#d3bc8d",
    "Seahawks" => "#69be2b",
    "Steelers" => "#ffb612",
    "Texans" => "#05354D",
    "Titans" => "#06192e",
    "Vikings" => "#4f2683",
    "TBD" => "#777777",
];

const NFL_TEAM_DIVISIONS = [
    "AFC East" => [
        "Bills",
        "Dolphins",
        "Jets",
        "Patriots",
    ],
    "AFC South" => [
        "Colts",
        "Jaguars",
        "Texans",
        "Titans",
    ],
    "AFC West" => [
        "Broncos",
        "Chargers",
        "Chiefs",
        "Raiders",
    ],
    "AFC North" => [
        "Bengals",
        "Browns",
        "Ravens",
        "Steelers",
    ],
    "NFC East" => [
        "Commanders",
        "Cowboys",
        "Eagles",
        "Giants",
    ],
    "NFC South" => [
        "Buccaneers",
        "Falcons",
        "Panthers",
        "Saints",
    ],
    "NFC West" => [
        "49ers",
        "Cardinals",
        "Rams",
        "Seahawks",
    ],
    "NFC North" => [
        "Bears",
        "Lions",
        "Packers",
        "Vikings",
    ],
];

const BL_TEAM_COLORS = [
    "Augsburg" => "#b92a1c",
    "Bayern" => "#c7282d",
    "Bochum" => "#2b5aa2",
    "Bremen" => "#52a66b",
    "BVB" => "#b39f08",
    "Darmstadt" => "#2f5dae",
    "Frankfurt" => "#c9291b",
    "Freiburg" => "#e40520",
    "Gladbach" => "#36703d",
    "Heidenheim" => "#d40201",
    "Hertha" => "#254b9c",
    "Hoffenheim" => "#3360b3",
    "Köln" => "#cb291a",
    "Leipzig" => "#da0034",
    "Leverkusen" => "#e52f19",
    "Mainz" => "#b0251e",
    "Schalke" => "#24499a",
    "Stuttgart" => "#c02626",
    "Union Berlin" => "#c02626",
    "Wolfsburg" => "#7bb23b",
];

const BL_TEAM_LINK_NAMES = [
    "Augsburg" => "fc-augsburg",
    "Bayern" => "fc-bayern-muenchen",
    "Bochum" => "vfl-bochum-1848",
    "Bremen" => "sv-werder-bremen",
    "BVB" => "borussia-dortmund",
    "Darmstadt" => "sv-darmstadt-98",
    "Frankfurt" => "eintracht-frankfurt",
    "Freiburg" => "sport-club-freiburg",
    "Gladbach" => "borussia-moenchengladbach",
    "Heidenheim" => "1-fc-heidenheim",
    "Hertha" => "hertha-bsc",
    "Hoffenheim" => "tsg-hoffenheim",
    "Köln" => "1-fc-koeln",
    "Leipzig" => "rb-leipzig",
    "Leverkusen" => "bayer-04-leverkusen",
    "Mainz" => "1-fsv-mainz-05",
    "Schalke" => "fc-schalke-04",
    "Stuttgart" => "vfb-stuttgart",
    "Union Berlin" => "1-fc-union-berlin",
    "Wolfsburg" => "vfl-wolfsburg",
];
?>
