<?php
const NFL_TEAM_COLORS = [
    "49ers" => "#aa0000",
    "Bears" => "#c73701",
    "Bengals" => "#fb4f14",
    "Bills" => "#00348d",
    "Broncos" => "#fb4f13",
    "Browns" => "#ff3c00",
    "Buccaneers" => "#a71930",
    "Cardinals" => "#97233f",
    "Chargers" => "#0080c6",
    "Chiefs" => "#e31837",
    "Colts" => "#002c5f",
    "Commanders" => "#5a1214",
    "Cowboys" => "#012244",
    "Dolphins" => "#008e97",
    "Eagles" => "#004c54",
    "Falcons" => "#a71930",
    "Giants" => "#0b2265",
    "Jaguars" => "#006375",
    "Jets" => "#003f2d",
    "Lions" => "#0076b6",
    "Packers" => "#203732",
    "Panthers" => "#0085ca",
    "Patriots" => "#003366",
    "Raiders" => "#090909",
    "Rams" => "#003594",
    "Ravens" => "#2b1c8c",
    "Saints" => "#d3bc8d",
    "Seahawks" => "#69be2b",
    "Steelers" => "#ffb612",
    "Texans" => "#05354D",
    "Titans" => "#06192e",
    "Vikings" => "#4f2683",
    "TBD" => "#777777",
];

const NFL_TEAM_DIVISIONS = [
    "AFC East" => [
        "Bills",
        "Dolphins",
        "Jets",
        "Patriots",
    ],
    "AFC South" => [
        "Colts",
        "Jaguars",
        "Texans",
        "Titans",
    ],
    "AFC West" => [
        "Broncos",
        "Chargers",
        "Chiefs",
        "Raiders",
    ],
    "AFC North" => [
        "Bengals",
        "Browns",
        "Ravens",
        "Steelers",
    ],
    "NFC East" => [
        "Commanders",
        "Cowboys",
        "Eagles",
        "Giants",
    ],
    "NFC South" => [
        "Buccaneers",
        "Falcons",
        "Panthers",
        "Saints",
    ],
    "NFC West" => [
        "49ers",
        "Cardinals",
        "Rams",
        "Seahawks",
    ],
    "NFC North" => [
        "Bears",
        "Lions",
        "Packers",
        "Vikings",
    ],
];
?>